In [17]:
import pandas as pd

In [18]:
df=pd.read_csv("C:/project/ecommerce_data.csv")
print(df)

        Order_ID  Order_Date  Customer_Name       City     Product  \
0      ORD116809  2024-02-07    Pooja Patel    Gurgaon     Monitor
1      ORD116171  2024-02-11   Vikas Sharma    Gurgaon  Headphones
2      ORD123118  2023-06-07  Nikhil Sharma    Gurgaon      Laptop
3      ORD123757  2024-11-16   Nikhil Patel    Lucknow      Laptop
4      ORD101588  2023-11-24    Aarav Singh  Hyderabad       Mouse
...          ...         ...            ...        ...         ...
30245  ORD129802  2025-06-25   Simran Patel      Ajmer         SSD
30246  ORD105390  2023-03-16    Kavya Mehta      Ajmer      Camera
30247  ORD100860  2025-02-23    Rahul Patel      Surat      Router
30248  ORD115795  2023-05-07    Aditi Patel     Mumbai      Webcam
30249  ORD123654  2024-08-12    Rohan Gupta     Jaipur     Earbuds

          Category  Quantity  Unit_Price  Discount      Sales Payment_Mode  \
0           Gaming       5.0    22061.08      0.05  104790.13  Net Banking
1      Accessories       4.0         NaN      0.30  305141.62  Net Banking
2           Gaming       3.0    51216.27      0.20  122919.05   Debit Card
3        Computers       7.0    54651.12      0.05  363429.95  Credit Card
4      Electronics       5.0    77021.50      0.00  385107.50          UPI
...            ...       ...         ...       ...        ...          ...
30245  Electronics       6.0    98283.87      0.15  501247.74       Wallet
30246       Gaming       6.0    76303.14      0.10  412036.96  Credit Card
30247  Electronics       4.0    59504.97      0.30  166613.92  Credit Card
30248       Gaming       5.0   114753.68      0.10  516391.56  Net Banking
30249    Computers       6.0   111887.19      0.25  503492.36  Net Banking

      Order_Status  Customer_Age  Rating  Delivery_Days
0        Delivered          25.0     3.0           12.0
1          Pending          31.0     1.0            3.0
2         Returned          65.0     3.0           14.0
3        Cancelled          22.0     4.0            8.0
4        delivered          31.0     2.0            1.0
...            ...           ...     ...            ...
30245      Shipped          29.0     1.0            8.0
30246     Returned          55.0     4.0            2.0
30247      Pending          66.0     1.0            NaN
30248    Cancelled          64.0     1.0            4.0
30249      Pending          31.0     2.0            4.0

[30250 rows x 15 columns]

In [19]:
df.head(5)

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
0,ORD116809,2024-02-07,Pooja Patel,Gurgaon,Monitor,Gaming,5.0,22061.08,0.05,104790.13,Net Banking,Delivered,25.0,3.0,12.0
1,ORD116171,2024-02-11,Vikas Sharma,Gurgaon,Headphones,Accessories,4.0,NaN,0.30,305141.62,Net Banking,Pending,31.0,1.0,3.0
2,ORD123118,2023-06-07,Nikhil Sharma,Gurgaon,Laptop,Gaming,3.0,51216.27,0.20,122919.05,Debit Card,Returned,65.0,3.0,14.0
3,ORD123757,2024-11-16,Nikhil Patel,Lucknow,Laptop,Computers,7.0,54651.12,0.05,363429.95,Credit Card,Cancelled,22.0,4.0,8.0
4,ORD101588,2023-11-24,Aarav Singh,Hyderabad,Mouse,Electronics,5.0,77021.50,0.00,385107.50,UPI,delivered,31.0,2.0,1.0

In [20]:
df.tail(10)

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
30240,ORD106265,2025-10-01,Nikhil Joshi,Mumbai,Monitor,Computers,5.0,98627.70,0.30,345196.95,Net Banking,Shipped,63.0,5.0,1.0
30241,ORD122118,2025-07-09,Rohan Jain,Noida,Smartwatch,Gaming,4.0,57810.57,0.25,173431.71,Debit Card,Shipped,53.0,3.0,1.0
30242,ORD111284,2023-07-15,Mohit Joshi,Sikar,Speaker,Computers,6.0,42535.34,0.00,255212.04,UPI,Returned,46.0,NaN,8.0
30243,ORD111964,2025-09-23,Rahul Mehta,Delhi,Webcam,Electronics,6.0,43077.89,0.15,219697.24,Debit Card,NaN,60.0,1.0,12.0
30244,ORD121575,2025-06-28,Sneha Singh,Udaipur,Webcam,Electronics,5.0,118574.30,0.25,444653.62,UPI,Shipped,42.0,4.0,8.0
30245,ORD129802,2025-06-25,Simran Patel,Ajmer,SSD,Electronics,6.0,98283.87,0.15,501247.74,Wallet,Shipped,29.0,1.0,8.0
30246,ORD105390,2023-03-16,Kavya Mehta,Ajmer,Camera,Gaming,6.0,76303.14,0.10,412036.96,Credit Card,Returned,55.0,4.0,2.0
30247,ORD100860,2025-02-23,Rahul Patel,Surat,Router,Electronics,4.0,59504.97,0.30,166613.92,Credit Card,Pending,66.0,1.0,NaN
30248,ORD115795,2023-05-07,Aditi Patel,Mumbai,Webcam,Gaming,5.0,114753.68,0.10,516391.56,Net Banking,Cancelled,64.0,1.0,4.0
30249,ORD123654,2024-08-12,Rohan Gupta,Jaipur,Earbuds,Computers,6.0,111887.19,0.25,503492.36,Net Banking,Pending,31.0,2.0,4.0

In [21]:
print(df.shape)

(30250, 15)

In [22]:
print(df.columns)

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'City', 'Product',
       'Category', 'Quantity', 'Unit_Price', 'Discount', 'Sales',
       'Payment_Mode', 'Order_Status', 'Customer_Age', 'Rating',
       'Delivery_Days'],
      dtype='object')

In [23]:
print(df.dtypes)

Order_ID          object
Order_Date        object
Customer_Name     object
City              object
Product           object
Category          object
Quantity         float64
Unit_Price       float64
Discount         float64
Sales            float64
Payment_Mode      object
Order_Status      object
Customer_Age     float64
Rating           float64
Delivery_Days    float64
dtype: object

In [24]:
df.describe()

,Quantity,Unit_Price,Discount,Sales,Customer_Age,Rating,Delivery_Days
count,30069.000000,30028.000000,29999.000000,29945.000000,29900.000000,29797.000000,29947.000000
mean,4.186272,60239.819300,0.149475,204679.728622,43.716722,3.016344,7.616422
std,4.748321,34602.871499,0.099881,169434.851700,15.311417,1.437808,5.182616
min,-1.000000,301.110000,0.000000,210.780000,5.000000,0.000000,0.000000
25%,2.000000,30499.980000,0.050000,68711.690000,31.000000,2.000000,4.000000
50%,4.000000,60198.065000,0.150000,158741.350000,44.000000,3.000000,7.000000
75%,6.000000,90260.292500,0.250000,303939.200000,57.000000,4.000000,11.000000
max,100.000000,119996.870000,0.300000,839697.250000,120.000000,10.000000,100.000000

In [25]:
print(df.isnull().sum())

Order_ID           0
Order_Date       251
Customer_Name    356
City             304
Product          252
Category         203
Quantity         181
Unit_Price       222
Discount         251
Sales            305
Payment_Mode     254
Order_Status     200
Customer_Age     350
Rating           453
Delivery_Days    303
dtype: int64

In [26]:
print(df.duplicated().sum())

250

In [27]:
print(df[df["Quantity"]>5])

        Order_ID  Order_Date  Customer_Name       City       Product  \
3      ORD123757  2024-11-16   Nikhil Patel    Lucknow        Laptop
9      ORD125221  2025-07-28   Simran Mehta      Delhi     USB Cable
12     ORD104672  2024-01-07   Simran Verma  Ahmedabad         Mouse
13     ORD110016  2023-10-25  Kavya Agarwal      Sikar        Webcam
16     ORD116196  2024-03-24    Anjali Jain      Noida  Mobile Phone
...          ...         ...            ...        ...           ...
30242  ORD111284  2023-07-15    Mohit Joshi      Sikar       Speaker
30243  ORD111964  2025-09-23    Rahul Mehta      Delhi        Webcam
30245  ORD129802  2025-06-25   Simran Patel      Ajmer           SSD
30246  ORD105390  2023-03-16    Kavya Mehta      Ajmer        Camera
30249  ORD123654  2024-08-12    Rohan Gupta     Jaipur       Earbuds

          Category  Quantity  Unit_Price  Discount      Sales Payment_Mode  \
3        Computers       7.0    54651.12      0.05  363429.95  Credit Card
9           Mobile       6.0    61307.59      0.15  312668.71  Net Banking
12          Gaming       7.0   101714.33      0.20  569600.25  Net Banking
13          Gaming       7.0    83752.78      0.30  410388.62  Credit Card
16          Gaming       6.0    78684.23      0.10  424894.84         Cash
...            ...       ...         ...       ...        ...          ...
30242    Computers       6.0    42535.34      0.00  255212.04          UPI
30243  Electronics       6.0    43077.89      0.15  219697.24   Debit Card
30245  Electronics       6.0    98283.87      0.15  501247.74       Wallet
30246       Gaming       6.0    76303.14      0.10  412036.96  Credit Card
30249    Computers       6.0   111887.19      0.25  503492.36  Net Banking

      Order_Status  Customer_Age  Rating  Delivery_Days
3        Cancelled          22.0     4.0            8.0
9         Returned          55.0     1.0            8.0
12         Shipped          68.0     5.0            1.0
13         Shipped          22.0     3.0            7.0
16         Pending          46.0     4.0            4.0
...            ...           ...     ...            ...
30242     Returned          46.0     NaN            8.0
30243          NaN          60.0     1.0           12.0
30245      Shipped          29.0     1.0            8.0
30246     Returned          55.0     4.0            2.0
30249      Pending          31.0     2.0            4.0

[8656 rows x 15 columns]

In [28]:
df= df[df["City"] == "Jaipur"]
print(df)

        Order_ID  Order_Date  Customer_Name    City       Product  \
7      ORD110959  2024-08-23    Simran Jain  Jaipur    Smartwatch
20     ORD105284  2023-09-23    Kavya Mehta  Jaipur     Hard Disk
57     ORD127876  2023-04-07    Aarav Verma  Jaipur        Camera
98     ORD106909  2024-03-17  Karan Agarwal  Jaipur  Gaming Chair
122    ORD100622  2023-01-21    Rahul Gupta  Jaipur     USB Cable
...          ...         ...            ...     ...           ...
30160  ORD113417  2023-07-18     Neha Gupta  Jaipur         Mouse
30166  ORD103943  2024-03-07   Anjali Verma  Jaipur  Gaming Chair
30184  ORD111016  2025-03-05    Amit Sharma  Jaipur     USB Cable
30221  ORD106420  2023-09-14    Sneha Singh  Jaipur    Smartwatch
30249  ORD123654  2024-08-12    Rohan Gupta  Jaipur       Earbuds

          Category  Quantity  Unit_Price  Discount      Sales Payment_Mode  \
7      Electronics       2.0    87304.23      0.05  165878.04         Cash
20     Accessories       2.0    39138.52      0.05   74363.19         Cash
57       Computers       3.0    92085.50      0.20  221005.20       Wallet
98     Electronics       2.0    34613.70      0.15   58843.29         Cash
122    Electronics       5.0    52860.80      0.05  251088.80          UPI
...            ...       ...         ...       ...        ...          ...
30160       Gaming       1.0    49485.73      0.20   39588.58         Cash
30166  Accessories       5.0     4056.90      0.20   16227.60  Net Banking
30184    Computers       7.0     3728.30      0.00   26098.10          UPI
30221  Electronics       7.0    69956.77      0.30  342788.17   Debit Card
30249    Computers       6.0   111887.19      0.25  503492.36  Net Banking

      Order_Status  Customer_Age  Rating  Delivery_Days
7        Delivered          33.0     1.0            7.0
20       Cancelled          49.0     2.0           14.0
57        Returned          60.0     1.0            3.0
98       Cancelled          40.0     3.0            4.0
122        Pending          58.0     1.0            7.0
...            ...           ...     ...            ...
30160    Cancelled          46.0     5.0            3.0
30166     Returned          18.0     3.0            1.0
30184     Returned          48.0     3.0            7.0
30221      Shipped          31.0     5.0           11.0
30249      Pending          31.0     2.0            4.0

[1383 rows x 15 columns]

In [29]:
df[df["Sales"]>50000]

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
7,ORD110959,2024-08-23,Simran Jain,Jaipur,Smartwatch,Electronics,2.0,87304.23,0.05,165878.04,Cash,Delivered,33.0,1.0,7.0
20,ORD105284,2023-09-23,Kavya Mehta,Jaipur,Hard Disk,Accessories,2.0,39138.52,0.05,74363.19,Cash,Cancelled,49.0,2.0,14.0
57,ORD127876,2023-04-07,Aarav Verma,Jaipur,Camera,Computers,3.0,92085.50,0.20,221005.20,Wallet,Returned,60.0,1.0,3.0
98,ORD106909,2024-03-17,Karan Agarwal,Jaipur,Gaming Chair,Electronics,2.0,34613.70,0.15,58843.29,Cash,Cancelled,40.0,3.0,4.0
122,ORD100622,2023-01-21,Rahul Gupta,Jaipur,USB Cable,Electronics,5.0,52860.80,0.05,251088.80,UPI,Pending,58.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30086,ORD114948,2023-09-16,Sneha Jain,Jaipur,Gaming Chair,Mobile,7.0,10609.59,0.25,55700.35,Wallet,Cancelled,65.0,4.0,13.0
30109,ORD129090,2024-02-18,Kavya Khan,Jaipur,Smartwatch,Electronics,3.0,44780.14,0.30,94038.29,Credit Card,Shipped,63.0,4.0,8.0
30145,ORD128374,2025-01-19,Sneha Jain,Jaipur,Speaker,Mobile,2.0,85849.69,0.15,145944.47,Wallet,Cancelled,23.0,2.0,10.0
30221,ORD106420,2023-09-14,Sneha Singh,Jaipur,Smartwatch,Electronics,7.0,69956.77,0.30,342788.17,Debit Card,Shipped,31.0,5.0,11.0
30249,ORD123654,2024-08-12,Rohan Gupta,Jaipur,Earbuds,Computers,6.0,111887.19,0.25,503492.36,Net Banking,Pending,31.0,2.0,4.0

In [30]:
df[df["Order_Status"] == "Delivered"]

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
7,ORD110959,2024-08-23,Simran Jain,Jaipur,Smartwatch,Electronics,2.0,87304.23,0.05,165878.04,Cash,Delivered,33.0,1.0,7.0
158,ORD108504,2025-12-11,Amit Patel,Jaipur,Earbuds,Electronics,7.0,64676.14,0.10,407459.68,Debit Card,Delivered,24.0,5.0,4.0
287,ORD105225,2025-07-18,Rahul Khan,Jaipur,Earbuds,Electronics,3.0,43872.12,0.10,118454.72,Wallet,Delivered,50.0,1.0,1.0
305,ORD124539,2024-01-13,Priya Gupta,Jaipur,Keyboard,Mobile,2.0,70984.01,0.05,134869.62,Cash,Delivered,39.0,2.0,1.0
310,ORD119432,04/01/2025,Pooja Khan,Jaipur,SSD,Accessories,4.0,91705.80,0.20,293458.56,Net Banking,Delivered,35.0,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29580,ORD126144,2025-07-14,Neha Patel,Jaipur,Router,Gaming,6.0,109602.88,0.25,493212.96,UPI,Delivered,53.0,2.0,5.0
29656,ORD107805,2023-01-22,Kavya Mehta,Jaipur,USB Cable,Accessories,4.0,837.84,0.10,3016.22,Debit Card,Delivered,43.0,3.0,7.0
29665,ORD123944,2023-09-16,Nikhil Sharma,Jaipur,Desk,Computers,6.0,46482.02,0.10,251002.91,Cash,Delivered,20.0,4.0,4.0
29905,ORD129945,2023-10-19,Neha Joshi,Jaipur,Laptop,Electronics,7.0,117187.26,0.00,820310.82,Wallet,Delivered,37.0,4.0,9.0
29974,ORD105855,2025-12-29,Aarav Gupta,Jaipur,Camera,Gaming,5.0,50602.18,0.25,189758.18,Credit Card,Delivered,48.0,5.0,14.0

In [31]:
df["City"].nunique()

1

In [32]:
print("Unique Cities:" , df["City"].nunique())

Unique Cities: 1

In [33]:
print("Payment Modes:", df["Payment_Mode"].unique())

Payment Modes: ['Cash' 'Wallet' 'UPI' 'Credit Card' 'Debit Card' 'Net Banking'
 'debit card' nan 'upi' 'Credit card']

In [34]:
print("Average Sales:" , df["Sales"].mean())

Average Sales: 210952.5750474799

In [35]:
# Questions

In [36]:
df.groupby("City")["Sales"].sum()

City
Jaipur    2.887941e+08
Name: Sales, dtype: float64

In [37]:
df.groupby("Category")["Sales"].mean()

Category
Accessories    200216.388939
Computers      199666.136948
Electronics    215814.716742
Gaming         197733.376283
Mobile         238543.769885
accessories    396445.264000
computers      146881.560000
electronics    163410.520000
gaming         447550.430000
mobile         182109.502000
Name: Sales, dtype: float64

In [38]:
df.groupby("Product")["Quantity"].sum()

Product
Camera          406.0
Desk            222.0
Earbuds         243.0
Gaming Chair    314.0
Hard Disk       265.0
Headphones      277.0
Keyboard        225.0
Laptop          389.0
Mobile Phone    268.0
Monitor         330.0
Mouse           249.0
Power Bank      311.0
Printer         249.0
Router          199.0
SSD             255.0
Smartwatch      259.0
Speaker         392.0
Tablet          302.0
USB Cable       330.0
Webcam          283.0
camera            9.0
desk             10.0
hard disk         1.0
laptop            9.0
mobile phone      5.0
monitor          13.0
mouse             5.0
power bank        6.0
printer           3.0
router           12.0
smartwatch       16.0
tablet           16.0
usb cable         3.0
Name: Quantity, dtype: float64

In [39]:
df.groupby("Payment_Mode").agg({
    "Sales":["sum","mean"],
    "Quantity":"sum"})

                    Sales                Quantity
                      sum           mean      sum
Payment_Mode
Cash          42354363.01  187408.685885    869.0
Credit Card   50901208.69  207760.035469   1000.0
Credit card    1557036.72  311407.344000     25.0
Debit Card    47327514.48  215125.065818    943.0
Net Banking   54077836.74  239282.463451   1033.0
UPI           43489990.74  200414.703871   1042.0
Wallet        44998295.61  212256.111368    923.0
debit card      804272.48  268090.826667     16.0
upi             529625.51  264812.755000      9.0

In [40]:
df["Order_Status"].value_counts()

Order_Status
Pending      288
Returned     276
Cancelled    267
Shipped      262
Delivered    257
delivered      6
 SHIPPED       5
PENDING        4
returned       4
cancelled      1
Name: count, dtype: int64

In [41]:
df["Payment_Mode"].value_counts()

Payment_Mode
Credit Card    251
Cash           228
Net Banking    227
Debit Card     224
UPI            218
Wallet         212
Credit card      5
debit card       3
upi              2
Name: count, dtype: int64

In [42]:
df["Product"].value_counts().head(10)

Product
Camera          78
Monitor         78
Gaming Chair    75
Tablet          75
Webcam          74
Speaker         73
Power Bank      73
Headphones      71
Laptop          69
Hard Disk       68
Name: count, dtype: int64

In [43]:
df["City"].value_counts()

City
Jaipur    1383
Name: count, dtype: int64

In [44]:
df.nlargest(10,"Sales")

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
29905,ORD129945,2023-10-19,Neha Joshi,Jaipur,Laptop,Electronics,7.0,117187.26,0.00,820310.82,Wallet,Delivered,37.0,4.0,9.0
29086,ORD116748,2023-10-11,Nikhil Sharma,Jaipur,Headphones,Accessories,7.0,114753.00,0.00,803271.00,Net Banking,Pending,45.0,2.0,7.0
25376,ORD129790,2025-05-03,Aarav Agarwal,Jaipur,Camera,Computers,7.0,112967.70,0.00,790773.90,Net Banking,Returned,44.0,4.0,5.0
15823,ORD122381,2023-10-28,Priya Sharma,Jaipur,Monitor,Mobile,7.0,117745.65,0.05,783008.57,Credit Card,Pending,33.0,3.0,10.0
9194,ORD122960,2024-02-18,Amit Mehta,Jaipur,Desk,Electronics,7.0,117377.96,0.05,780563.43,Wallet,Cancelled,66.0,1.0,1.0
27468,ORD101316,2024-08-10,Pooja Gupta,Jaipur,Power Bank,Mobile,7.0,110463.33,0.00,773243.31,Net Banking,SHIPPED,28.0,1.0,4.0
4693,ORD110563,2024-01-05,Karan Sharma,Jaipur,Printer,Electronics,7.0,114594.52,0.05,762053.56,UPI,Cancelled,38.0,5.0,5.0
12455,ORD104941,2025-09-11,Kavya Joshi,Jaipur,Camera,Mobile,7.0,119853.88,0.10,755079.44,Credit Card,Pending,23.0,4.0,14.0
5063,ORD115594,2024-01-01,Kavya Agarwal,Jaipur,Smartwatch,Gaming,7.0,106759.18,0.00,747314.26,Net Banking,Returned,36.0,4.0,NaN
24590,ORD120884,2024-01-11,Sneha Joshi,Jaipur,Speaker,Mobile,7.0,109141.14,0.05,725788.58,Debit Card,Cancelled,38.0,2.0,5.0

In [45]:
df.sort_values("Rating", ascending=False)

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
12844,ORD127487,2025-04-01,Nikhil Mehta,Jaipur,Webcam,Mobile,2.0,67128.93,0.25,100693.39,Wallet,Delivered,46.0,10.0,9.0
7432,ORD127640,2023-04-16,Nikhil Gupta,Jaipur,Gaming Chair,Gaming,1.0,100171.73,0.15,85145.97,Cash,Cancelled,30.0,10.0,13.0
5910,ORD113610,2024-08-07,Rohan Sharma,Jaipur,Desk,Electronics,2.0,76398.20,0.15,129876.94,Wallet,Cancelled,59.0,10.0,3.0
25118,ORD122742,2025-05-31,Kavya Joshi,Jaipur,Router,Electronics,3.0,76139.30,0.30,159892.53,Net Banking,Shipped,63.0,6.0,10.0
15944,ORD124588,2024-10-21,Neha Khan,Jaipur,Router,Computers,1.0,113133.02,0.00,113133.02,UPI,NaN,55.0,6.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24736,ORD118949,2024-01-21,Rohan Agarwal,Jaipur,Headphones,Electronics,6.0,48438.24,0.30,203440.61,Net Banking,Delivered,56.0,NaN,6.0
24804,ORD125746,2023-07-15,Mohit Jain,Jaipur,Keyboard,Gaming,1.0,54823.88,0.30,38376.72,Wallet,Cancelled,48.0,NaN,6.0
24987,ORD114631,2023-04-10,Pooja Verma,Jaipur,Keyboard,Accessories,3.0,106896.02,0.00,320688.06,Wallet,Returned,35.0,NaN,7.0
25734,ORD100522,2023-02-25,Mohit Gupta,Jaipur,Camera,Mobile,2.0,97327.31,0.30,136258.23,Credit Card,Pending,35.0,NaN,12.0
27980,ORD116500,2024-05-02,Vikas Jain,Jaipur,Headphones,Computers,7.0,96575.39,0.30,473219.41,UPI,Pending,33.0,NaN,1.0

In [46]:
df.nlargest(10, "Delivery_Days")

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
7657,ORD127802,2024-05-27,Simran Joshi,Jaipur,Smartwatch,Computers,1.0,39926.90,0.25,29945.18,UPI,Shipped,48.0,2.0,60.0
20,ORD105284,2023-09-23,Kavya Mehta,Jaipur,Hard Disk,Accessories,2.0,39138.52,0.05,74363.19,Cash,Cancelled,49.0,2.0,14.0
592,ORD104186,2023-12-16,Rohan Jain,Jaipur,Printer,Gaming,2.0,65984.98,0.20,105575.97,Cash,Returned,54.0,5.0,14.0
684,ORD128185,2023-06-18,Simran Jain,Jaipur,Power Bank,Accessories,4.0,18778.71,0.25,56336.13,Debit Card,Cancelled,65.0,3.0,14.0
1192,ORD123376,2023-10-01,Aarav Singh,Jaipur,USB Cable,Gaming,6.0,82690.72,0.10,446529.89,Cash,Cancelled,47.0,4.0,14.0
1414,ORD101053,2023-02-13,Mohit Verma,Jaipur,USB Cable,Gaming,5.0,79168.81,0.00,395844.05,Wallet,PENDING,27.0,1.0,14.0
1466,ORD117542,2025-09-07,Aarav Jain,Jaipur,Camera,Electronics,2.0,72855.74,0.05,138425.91,Net Banking,Returned,55.0,5.0,14.0
1699,ORD116556,2024-08-12,Pooja Singh,Jaipur,Mobile Phone,Electronics,1.0,90480.03,0.15,76908.03,Debit Card,Returned,35.0,5.0,14.0
2017,ORD116273,2025-05-27,Pooja Agarwal,Jaipur,Tablet,Mobile,2.0,92078.59,0.30,128910.03,Debit Card,Returned,67.0,3.0,14.0
2391,ORD116219,2025-03-21,Simran Jain,Jaipur,Monitor,Mobile,5.0,101483.61,0.00,507418.05,UPI,Delivered,37.0,4.0,14.0

In [47]:
df["Customer_Age"] = df["Customer_Age"].fillna(
    df["Customer_Age"].mean()
)

In [48]:
df["Customer_Age"]

7        33.0
20       49.0
57       60.0
98       40.0
122      58.0
         ...
30160    46.0
30166    18.0
30184    48.0
30221    31.0
30249    31.0
Name: Customer_Age, Length: 1383, dtype: float64

In [49]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
7,ORD110959,2024-08-23,Simran Jain,Jaipur,Smartwatch,Electronics,2.0,87304.23,0.05,165878.04,Cash,Delivered,33.0,1.0,7.0
20,ORD105284,2023-09-23,Kavya Mehta,Jaipur,Hard Disk,Accessories,2.0,39138.52,0.05,74363.19,Cash,Cancelled,49.0,2.0,14.0
57,ORD127876,2023-04-07,Aarav Verma,Jaipur,Camera,Computers,3.0,92085.50,0.20,221005.20,Wallet,Returned,60.0,1.0,3.0
98,ORD106909,2024-03-17,Karan Agarwal,Jaipur,Gaming Chair,Electronics,2.0,34613.70,0.15,58843.29,Cash,Cancelled,40.0,3.0,4.0
122,ORD100622,2023-01-21,Rahul Gupta,Jaipur,USB Cable,Electronics,5.0,52860.80,0.05,251088.80,UPI,Pending,58.0,1.0,7.0

In [50]:
df["Rating"] = df["Rating"].fillna(df["Rating"].median())

In [51]:
df["Rating"].isnull().sum()

np.int64(0)

In [52]:
df["Payment_Mode"].isnull().sum()

np.int64(13)

In [53]:
df.duplicated().sum()

np.int64(9)

In [54]:
df=df.drop_duplicates()

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df["Order_ID"].duplicated()

7        False
20       False
57       False
98       False
122      False
         ...
30160    False
30166    False
30184    False
30221    False
30249    False
Name: Order_ID, Length: 1374, dtype: bool

In [57]:
df=df.drop_duplicates(subset="Order_ID",keep="first")

In [58]:
print(df)

        Order_ID  Order_Date  Customer_Name    City       Product  \
7      ORD110959  2024-08-23    Simran Jain  Jaipur    Smartwatch
20     ORD105284  2023-09-23    Kavya Mehta  Jaipur     Hard Disk
57     ORD127876  2023-04-07    Aarav Verma  Jaipur        Camera
98     ORD106909  2024-03-17  Karan Agarwal  Jaipur  Gaming Chair
122    ORD100622  2023-01-21    Rahul Gupta  Jaipur     USB Cable
...          ...         ...            ...     ...           ...
30160  ORD113417  2023-07-18     Neha Gupta  Jaipur         Mouse
30166  ORD103943  2024-03-07   Anjali Verma  Jaipur  Gaming Chair
30184  ORD111016  2025-03-05    Amit Sharma  Jaipur     USB Cable
30221  ORD106420  2023-09-14    Sneha Singh  Jaipur    Smartwatch
30249  ORD123654  2024-08-12    Rohan Gupta  Jaipur       Earbuds

          Category  Quantity  Unit_Price  Discount      Sales Payment_Mode  \
7      Electronics       2.0    87304.23      0.05  165878.04         Cash
20     Accessories       2.0    39138.52      0.05   74363.19         Cash
57       Computers       3.0    92085.50      0.20  221005.20       Wallet
98     Electronics       2.0    34613.70      0.15   58843.29         Cash
122    Electronics       5.0    52860.80      0.05  251088.80          UPI
...            ...       ...         ...       ...        ...          ...
30160       Gaming       1.0    49485.73      0.20   39588.58         Cash
30166  Accessories       5.0     4056.90      0.20   16227.60  Net Banking
30184    Computers       7.0     3728.30      0.00   26098.10          UPI
30221  Electronics       7.0    69956.77      0.30  342788.17   Debit Card
30249    Computers       6.0   111887.19      0.25  503492.36  Net Banking

      Order_Status  Customer_Age  Rating  Delivery_Days
7        Delivered          33.0     1.0            7.0
20       Cancelled          49.0     2.0           14.0
57        Returned          60.0     1.0            3.0
98       Cancelled          40.0     3.0            4.0
122        Pending          58.0     1.0            7.0
...            ...           ...     ...            ...
30160    Cancelled          46.0     5.0            3.0
30166     Returned          18.0     3.0            1.0
30184     Returned          48.0     3.0            7.0
30221      Shipped          31.0     5.0           11.0
30249      Pending          31.0     2.0            4.0

[1374 rows x 15 columns]

In [59]:
df.sort_values( "Delivery_Days",ascending=False).head(10)

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Sales,Payment_Mode,Order_Status,Customer_Age,Rating,Delivery_Days
7657,ORD127802,2024-05-27,Simran Joshi,Jaipur,Smartwatch,Computers,1.0,39926.90,0.25,29945.18,UPI,Shipped,48.00000,2.0,60.0
16601,ORD109613,2025-10-15,Priya Agarwal,Jaipur,Gaming Chair,Gaming,7.0,66034.03,0.30,323566.75,Net Banking,Pending,20.00000,2.0,14.0
20969,ORD115682,2025-11-13,Mohit Khan,Jaipur,Mouse,Electronics,7.0,22502.99,0.20,126016.74,Credit Card,Pending,41.00000,1.0,14.0
11082,ORD123949,2025-03-29,Vikas Sharma,Jaipur,Power Bank,Gaming,5.0,104023.80,0.10,468107.10,Cash,Cancelled,42.00000,2.0,14.0
21226,ORD104067,2024-06-23,Priya Sharma,Jaipur,Gaming Chair,Accessories,5.0,25364.68,0.15,107799.89,Net Banking,Shipped,62.00000,2.0,14.0
10722,ORD101905,2023-08-12,Aarav Joshi,Jaipur,Headphones,Accessories,7.0,5011.32,0.30,24555.47,Debit Card,Returned,35.00000,5.0,14.0
10482,ORD113955,2024-01-06,Neha Khan,Jaipur,Earbuds,Accessories,6.0,101243.16,0.15,516340.12,Cash,PENDING,44.00000,4.0,14.0
10046,ORD100711,2023-05-04,Aditi Gupta,Jaipur,Speaker,Electronics,7.0,76675.36,0.25,402545.64,Net Banking,Pending,44.04182,6.0,14.0
21945,ORD108963,2025-04-10,Neha Sharma,Jaipur,Webcam,Computers,4.0,106875.96,0.20,342003.07,Net Banking,Shipped,67.00000,2.0,14.0
21997,ORD103908,2024-08-24,Kavya Sharma,Jaipur,Webcam,Mobile,1.0,116933.38,0.25,87700.04,Cash,Cancelled,40.00000,2.0,14.0

In [60]:
print(df['Order_Date'].head())

7      2024-08-23
20     2023-09-23
57     2023-04-07
98     2024-03-17
122    2023-01-21
Name: Order_Date, dtype: object

In [63]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors = 'coerce')

In [64]:
print(df)

        Order_ID Order_Date  Customer_Name    City       Product     Category  \
7      ORD110959 2024-08-23    Simran Jain  Jaipur    Smartwatch  Electronics
20     ORD105284 2023-09-23    Kavya Mehta  Jaipur     Hard Disk  Accessories
57     ORD127876 2023-04-07    Aarav Verma  Jaipur        Camera    Computers
98     ORD106909 2024-03-17  Karan Agarwal  Jaipur  Gaming Chair  Electronics
122    ORD100622 2023-01-21    Rahul Gupta  Jaipur     USB Cable  Electronics
...          ...        ...            ...     ...           ...          ...
30160  ORD113417 2023-07-18     Neha Gupta  Jaipur         Mouse       Gaming
30166  ORD103943 2024-03-07   Anjali Verma  Jaipur  Gaming Chair  Accessories
30184  ORD111016 2025-03-05    Amit Sharma  Jaipur     USB Cable    Computers
30221  ORD106420 2023-09-14    Sneha Singh  Jaipur    Smartwatch  Electronics
30249  ORD123654 2024-08-12    Rohan Gupta  Jaipur       Earbuds    Computers

       Quantity  Unit_Price  Discount      Sales Payment_Mode Order_Status  \
7           2.0    87304.23      0.05  165878.04         Cash    Delivered
20          2.0    39138.52      0.05   74363.19         Cash    Cancelled
57          3.0    92085.50      0.20  221005.20       Wallet     Returned
98          2.0    34613.70      0.15   58843.29         Cash    Cancelled
122         5.0    52860.80      0.05  251088.80          UPI      Pending
...         ...         ...       ...        ...          ...          ...
30160       1.0    49485.73      0.20   39588.58         Cash    Cancelled
30166       5.0     4056.90      0.20   16227.60  Net Banking     Returned
30184       7.0     3728.30      0.00   26098.10          UPI     Returned
30221       7.0    69956.77      0.30  342788.17   Debit Card      Shipped
30249       6.0   111887.19      0.25  503492.36  Net Banking      Pending

       Customer_Age  Rating  Delivery_Days
7              33.0     1.0            7.0
20             49.0     2.0           14.0
57             60.0     1.0            3.0
98             40.0     3.0            4.0
122            58.0     1.0            7.0
...             ...     ...            ...
30160          46.0     5.0            3.0
30166          18.0     3.0            1.0
30184          48.0     3.0            7.0
30221          31.0     5.0           11.0
30249          31.0     2.0            4.0

[1374 rows x 15 columns]

In [65]:
print(df['Order_Date'].dtype)

datetime64[ns]

In [74]:
df['Order_Year'] = df['Order_Date'].dt.year

In [75]:
print(df)

        Order_ID Order_Date  Customer_Name    City       Product     Category  \
7      ORD110959 2024-08-23    Simran Jain  Jaipur    Smartwatch  Electronics
20     ORD105284 2023-09-23    Kavya Mehta  Jaipur     Hard Disk  Accessories
57     ORD127876 2023-04-07    Aarav Verma  Jaipur        Camera    Computers
98     ORD106909 2024-03-17  Karan Agarwal  Jaipur  Gaming Chair  Electronics
122    ORD100622 2023-01-21    Rahul Gupta  Jaipur     USB Cable  Electronics
...          ...        ...            ...     ...           ...          ...
30160  ORD113417 2023-07-18     Neha Gupta  Jaipur         Mouse       Gaming
30166  ORD103943 2024-03-07   Anjali Verma  Jaipur  Gaming Chair  Accessories
30184  ORD111016 2025-03-05    Amit Sharma  Jaipur     USB Cable    Computers
30221  ORD106420 2023-09-14    Sneha Singh  Jaipur    Smartwatch  Electronics
30249  ORD123654 2024-08-12    Rohan Gupta  Jaipur       Earbuds    Computers

       Quantity  Unit_Price  Discount      Sales Payment_Mode Order_Status  \
7           2.0    87304.23      0.05  165878.04         Cash    Delivered
20          2.0    39138.52      0.05   74363.19         Cash    Cancelled
57          3.0    92085.50      0.20  221005.20       Wallet     Returned
98          2.0    34613.70      0.15   58843.29         Cash    Cancelled
122         5.0    52860.80      0.05  251088.80          UPI      Pending
...         ...         ...       ...        ...          ...          ...
30160       1.0    49485.73      0.20   39588.58         Cash    Cancelled
30166       5.0     4056.90      0.20   16227.60  Net Banking     Returned
30184       7.0     3728.30      0.00   26098.10          UPI     Returned
30221       7.0    69956.77      0.30  342788.17   Debit Card      Shipped
30249       6.0   111887.19      0.25  503492.36  Net Banking      Pending

       Customer_Age  Rating  Delivery_Days  Order_Year  Order_Month  Order_
7              33.0     1.0            7.0      2024.0          8.0  2024.0
20             49.0     2.0           14.0      2023.0          9.0  2023.0
57             60.0     1.0            3.0      2023.0          4.0  2023.0
98             40.0     3.0            4.0      2024.0          3.0  2024.0
122            58.0     1.0            7.0      2023.0          1.0  2023.0
...             ...     ...            ...         ...          ...     ...
30160          46.0     5.0            3.0      2023.0          7.0  2023.0
30166          18.0     3.0            1.0      2024.0          3.0  2024.0
30184          48.0     3.0            7.0      2025.0          3.0  2025.0
30221          31.0     5.0           11.0      2023.0          9.0  2023.0
30249          31.0     2.0            4.0      2024.0          8.0  2024.0

[1374 rows x 18 columns]

In [76]:
df['Order_Month'] = df['Order_Date'].dt.month

In [77]:
print(df)

        Order_ID Order_Date  Customer_Name    City       Product     Category  \
7      ORD110959 2024-08-23    Simran Jain  Jaipur    Smartwatch  Electronics
20     ORD105284 2023-09-23    Kavya Mehta  Jaipur     Hard Disk  Accessories
57     ORD127876 2023-04-07    Aarav Verma  Jaipur        Camera    Computers
98     ORD106909 2024-03-17  Karan Agarwal  Jaipur  Gaming Chair  Electronics
122    ORD100622 2023-01-21    Rahul Gupta  Jaipur     USB Cable  Electronics
...          ...        ...            ...     ...           ...          ...
30160  ORD113417 2023-07-18     Neha Gupta  Jaipur         Mouse       Gaming
30166  ORD103943 2024-03-07   Anjali Verma  Jaipur  Gaming Chair  Accessories
30184  ORD111016 2025-03-05    Amit Sharma  Jaipur     USB Cable    Computers
30221  ORD106420 2023-09-14    Sneha Singh  Jaipur    Smartwatch  Electronics
30249  ORD123654 2024-08-12    Rohan Gupta  Jaipur       Earbuds    Computers

       Quantity  Unit_Price  Discount      Sales Payment_Mode Order_Status  \
7           2.0    87304.23      0.05  165878.04         Cash    Delivered
20          2.0    39138.52      0.05   74363.19         Cash    Cancelled
57          3.0    92085.50      0.20  221005.20       Wallet     Returned
98          2.0    34613.70      0.15   58843.29         Cash    Cancelled
122         5.0    52860.80      0.05  251088.80          UPI      Pending
...         ...         ...       ...        ...          ...          ...
30160       1.0    49485.73      0.20   39588.58         Cash    Cancelled
30166       5.0     4056.90      0.20   16227.60  Net Banking     Returned
30184       7.0     3728.30      0.00   26098.10          UPI     Returned
30221       7.0    69956.77      0.30  342788.17   Debit Card      Shipped
30249       6.0   111887.19      0.25  503492.36  Net Banking      Pending

       Customer_Age  Rating  Delivery_Days  Order_Year  Order_Month  Order_
7              33.0     1.0            7.0      2024.0          8.0  2024.0
20             49.0     2.0           14.0      2023.0          9.0  2023.0
57             60.0     1.0            3.0      2023.0          4.0  2023.0
98             40.0     3.0            4.0      2024.0          3.0  2024.0
122            58.0     1.0            7.0      2023.0          1.0  2023.0
...             ...     ...            ...         ...          ...     ...
30160          46.0     5.0            3.0      2023.0          7.0  2023.0
30166          18.0     3.0            1.0      2024.0          3.0  2024.0
30184          48.0     3.0            7.0      2025.0          3.0  2025.0
30221          31.0     5.0           11.0      2023.0          9.0  2023.0
30249          31.0     2.0            4.0      2024.0          8.0  2024.0

[1374 rows x 18 columns]

In [79]:
df.groupby('Order_Year')['Sales'].sum()

Order_Year
2023.0    96507251.36
2024.0    91595749.67
2025.0    91662187.36
Name: Sales, dtype: float64

In [81]:
df['City'] = df['City'].str.strip().str.title()

In [82]:
print(df)

        Order_ID Order_Date  Customer_Name    City       Product     Category  \
7      ORD110959 2024-08-23    Simran Jain  Jaipur    Smartwatch  Electronics
20     ORD105284 2023-09-23    Kavya Mehta  Jaipur     Hard Disk  Accessories
57     ORD127876 2023-04-07    Aarav Verma  Jaipur        Camera    Computers
98     ORD106909 2024-03-17  Karan Agarwal  Jaipur  Gaming Chair  Electronics
122    ORD100622 2023-01-21    Rahul Gupta  Jaipur     USB Cable  Electronics
...          ...        ...            ...     ...           ...          ...
30160  ORD113417 2023-07-18     Neha Gupta  Jaipur         Mouse       Gaming
30166  ORD103943 2024-03-07   Anjali Verma  Jaipur  Gaming Chair  Accessories
30184  ORD111016 2025-03-05    Amit Sharma  Jaipur     USB Cable    Computers
30221  ORD106420 2023-09-14    Sneha Singh  Jaipur    Smartwatch  Electronics
30249  ORD123654 2024-08-12    Rohan Gupta  Jaipur       Earbuds    Computers

       Quantity  Unit_Price  Discount      Sales Payment_Mode Order_Status  \
7           2.0    87304.23      0.05  165878.04         Cash    Delivered
20          2.0    39138.52      0.05   74363.19         Cash    Cancelled
57          3.0    92085.50      0.20  221005.20       Wallet     Returned
98          2.0    34613.70      0.15   58843.29         Cash    Cancelled
122         5.0    52860.80      0.05  251088.80          UPI      Pending
...         ...         ...       ...        ...          ...          ...
30160       1.0    49485.73      0.20   39588.58         Cash    Cancelled
30166       5.0     4056.90      0.20   16227.60  Net Banking     Returned
30184       7.0     3728.30      0.00   26098.10          UPI     Returned
30221       7.0    69956.77      0.30  342788.17   Debit Card      Shipped
30249       6.0   111887.19      0.25  503492.36  Net Banking      Pending

       Customer_Age  Rating  Delivery_Days  Order_Year  Order_Month  Order_
7              33.0     1.0            7.0      2024.0          8.0  2024.0
20             49.0     2.0           14.0      2023.0          9.0  2023.0
57             60.0     1.0            3.0      2023.0          4.0  2023.0
98             40.0     3.0            4.0      2024.0          3.0  2024.0
122            58.0     1.0            7.0      2023.0          1.0  2023.0
...             ...     ...            ...         ...          ...     ...
30160          46.0     5.0            3.0      2023.0          7.0  2023.0
30166          18.0     3.0            1.0      2024.0          3.0  2024.0
30184          48.0     3.0            7.0      2025.0          3.0  2025.0
30221          31.0     5.0           11.0      2023.0          9.0  2023.0
30249          31.0     2.0            4.0      2024.0          8.0  2024.0

[1374 rows x 18 columns]

In [83]:
df['Product'] = df['Product'].str.strip().str.title()

In [84]:
print(df)

        Order_ID Order_Date  Customer_Name    City       Product     Category  \
7      ORD110959 2024-08-23    Simran Jain  Jaipur    Smartwatch  Electronics
20     ORD105284 2023-09-23    Kavya Mehta  Jaipur     Hard Disk  Accessories
57     ORD127876 2023-04-07    Aarav Verma  Jaipur        Camera    Computers
98     ORD106909 2024-03-17  Karan Agarwal  Jaipur  Gaming Chair  Electronics
122    ORD100622 2023-01-21    Rahul Gupta  Jaipur     Usb Cable  Electronics
...          ...        ...            ...     ...           ...          ...
30160  ORD113417 2023-07-18     Neha Gupta  Jaipur         Mouse       Gaming
30166  ORD103943 2024-03-07   Anjali Verma  Jaipur  Gaming Chair  Accessories
30184  ORD111016 2025-03-05    Amit Sharma  Jaipur     Usb Cable    Computers
30221  ORD106420 2023-09-14    Sneha Singh  Jaipur    Smartwatch  Electronics
30249  ORD123654 2024-08-12    Rohan Gupta  Jaipur       Earbuds    Computers

       Quantity  Unit_Price  Discount      Sales Payment_Mode Order_Status  \
7           2.0    87304.23      0.05  165878.04         Cash    Delivered
20          2.0    39138.52      0.05   74363.19         Cash    Cancelled
57          3.0    92085.50      0.20  221005.20       Wallet     Returned
98          2.0    34613.70      0.15   58843.29         Cash    Cancelled
122         5.0    52860.80      0.05  251088.80          UPI      Pending
...         ...         ...       ...        ...          ...          ...
30160       1.0    49485.73      0.20   39588.58         Cash    Cancelled
30166       5.0     4056.90      0.20   16227.60  Net Banking     Returned
30184       7.0     3728.30      0.00   26098.10          UPI     Returned
30221       7.0    69956.77      0.30  342788.17   Debit Card      Shipped
30249       6.0   111887.19      0.25  503492.36  Net Banking      Pending

       Customer_Age  Rating  Delivery_Days  Order_Year  Order_Month  Order_
7              33.0     1.0            7.0      2024.0          8.0  2024.0
20             49.0     2.0           14.0      2023.0          9.0  2023.0
57             60.0     1.0            3.0      2023.0          4.0  2023.0
98             40.0     3.0            4.0      2024.0          3.0  2024.0
122            58.0     1.0            7.0      2023.0          1.0  2023.0
...             ...     ...            ...         ...          ...     ...
30160          46.0     5.0            3.0      2023.0          7.0  2023.0
30166          18.0     3.0            1.0      2024.0          3.0  2024.0
30184          48.0     3.0            7.0      2025.0          3.0  2025.0
30221          31.0     5.0           11.0      2023.0          9.0  2023.0
30249          31.0     2.0            4.0      2024.0          8.0  2024.0

[1374 rows x 18 columns]

In [85]:
df['Payment_Mode'] = df['Payment_Mode'].str.strip().str.title()

In [86]:
print(df)

        Order_ID Order_Date  Customer_Name    City       Product     Category  \
7      ORD110959 2024-08-23    Simran Jain  Jaipur    Smartwatch  Electronics
20     ORD105284 2023-09-23    Kavya Mehta  Jaipur     Hard Disk  Accessories
57     ORD127876 2023-04-07    Aarav Verma  Jaipur        Camera    Computers
98     ORD106909 2024-03-17  Karan Agarwal  Jaipur  Gaming Chair  Electronics
122    ORD100622 2023-01-21    Rahul Gupta  Jaipur     Usb Cable  Electronics
...          ...        ...            ...     ...           ...          ...
30160  ORD113417 2023-07-18     Neha Gupta  Jaipur         Mouse       Gaming
30166  ORD103943 2024-03-07   Anjali Verma  Jaipur  Gaming Chair  Accessories
30184  ORD111016 2025-03-05    Amit Sharma  Jaipur     Usb Cable    Computers
30221  ORD106420 2023-09-14    Sneha Singh  Jaipur    Smartwatch  Electronics
30249  ORD123654 2024-08-12    Rohan Gupta  Jaipur       Earbuds    Computers

       Quantity  Unit_Price  Discount      Sales Payment_Mode Order_Status  \
7           2.0    87304.23      0.05  165878.04         Cash    Delivered
20          2.0    39138.52      0.05   74363.19         Cash    Cancelled
57          3.0    92085.50      0.20  221005.20       Wallet     Returned
98          2.0    34613.70      0.15   58843.29         Cash    Cancelled
122         5.0    52860.80      0.05  251088.80          Upi      Pending
...         ...         ...       ...        ...          ...          ...
30160       1.0    49485.73      0.20   39588.58         Cash    Cancelled
30166       5.0     4056.90      0.20   16227.60  Net Banking     Returned
30184       7.0     3728.30      0.00   26098.10          Upi     Returned
30221       7.0    69956.77      0.30  342788.17   Debit Card      Shipped
30249       6.0   111887.19      0.25  503492.36  Net Banking      Pending

       Customer_Age  Rating  Delivery_Days  Order_Year  Order_Month  Order_
7              33.0     1.0            7.0      2024.0          8.0  2024.0
20             49.0     2.0           14.0      2023.0          9.0  2023.0
57             60.0     1.0            3.0      2023.0          4.0  2023.0
98             40.0     3.0            4.0      2024.0          3.0  2024.0
122            58.0     1.0            7.0      2023.0          1.0  2023.0
...             ...     ...            ...         ...          ...     ...
30160          46.0     5.0            3.0      2023.0          7.0  2023.0
30166          18.0     3.0            1.0      2024.0          3.0  2024.0
30184          48.0     3.0            7.0      2025.0          3.0  2025.0
30221          31.0     5.0           11.0      2023.0          9.0  2023.0
30249          31.0     2.0            4.0      2024.0          8.0  2024.0

[1374 rows x 18 columns]

In [87]:
df['Order_Status'] = df['Order_Status'].str.strip().str.title()

In [88]:
print(df)

        Order_ID Order_Date  Customer_Name    City       Product     Category  \
7      ORD110959 2024-08-23    Simran Jain  Jaipur    Smartwatch  Electronics
20     ORD105284 2023-09-23    Kavya Mehta  Jaipur     Hard Disk  Accessories
57     ORD127876 2023-04-07    Aarav Verma  Jaipur        Camera    Computers
98     ORD106909 2024-03-17  Karan Agarwal  Jaipur  Gaming Chair  Electronics
122    ORD100622 2023-01-21    Rahul Gupta  Jaipur     Usb Cable  Electronics
...          ...        ...            ...     ...           ...          ...
30160  ORD113417 2023-07-18     Neha Gupta  Jaipur         Mouse       Gaming
30166  ORD103943 2024-03-07   Anjali Verma  Jaipur  Gaming Chair  Accessories
30184  ORD111016 2025-03-05    Amit Sharma  Jaipur     Usb Cable    Computers
30221  ORD106420 2023-09-14    Sneha Singh  Jaipur    Smartwatch  Electronics
30249  ORD123654 2024-08-12    Rohan Gupta  Jaipur       Earbuds    Computers

       Quantity  Unit_Price  Discount      Sales Payment_Mode Order_Status  \
7           2.0    87304.23      0.05  165878.04         Cash    Delivered
20          2.0    39138.52      0.05   74363.19         Cash    Cancelled
57          3.0    92085.50      0.20  221005.20       Wallet     Returned
98          2.0    34613.70      0.15   58843.29         Cash    Cancelled
122         5.0    52860.80      0.05  251088.80          Upi      Pending
...         ...         ...       ...        ...          ...          ...
30160       1.0    49485.73      0.20   39588.58         Cash    Cancelled
30166       5.0     4056.90      0.20   16227.60  Net Banking     Returned
30184       7.0     3728.30      0.00   26098.10          Upi     Returned
30221       7.0    69956.77      0.30  342788.17   Debit Card      Shipped
30249       6.0   111887.19      0.25  503492.36  Net Banking      Pending

       Customer_Age  Rating  Delivery_Days  Order_Year  Order_Month  Order_
7              33.0     1.0            7.0      2024.0          8.0  2024.0
20             49.0     2.0           14.0      2023.0          9.0  2023.0
57             60.0     1.0            3.0      2023.0          4.0  2023.0
98             40.0     3.0            4.0      2024.0          3.0  2024.0
122            58.0     1.0            7.0      2023.0          1.0  2023.0
...             ...     ...            ...         ...          ...     ...
30160          46.0     5.0            3.0      2023.0          7.0  2023.0
30166          18.0     3.0            1.0      2024.0          3.0  2024.0
30184          48.0     3.0            7.0      2025.0          3.0  2025.0
30221          31.0     5.0           11.0      2023.0          9.0  2023.0
30249          31.0     2.0            4.0      2024.0          8.0  2024.0

[1374 rows x 18 columns]